### ISSUE TITLE
Optimize the background image

### ISSUE THREAD

**Issue by w-b-dev** [w-b-dev/30min-todo-with-astra-db#14]

**Comment by w-b-dev** [comment]
https://www.digitalocean.com/community/tutorials/how-to-change-a-css-background-images-opacity

```html
<div class="demo-wrap">
  <img
    class="demo-bg"
    src="https://assets.digitalocean.com/labs/images/community_bg.png"
    alt=""
  >
  <div class="demo-content">
    <h1>Hello World!</h1>
  </div>
</div>
```

```css
.demo-wrap {
  overflow: hidden;
  position: relative;
}

.demo-bg {
  opacity: 0.6;
  position: absolute;
  left: 0;
  top: 0;
  width: 100%;
  height: auto;
}

.demo-content {
  position: relative;
}
```
